import type { Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs';
import Link from 'next/link';
import { ChartColumnBig } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Fraunces, Gabriela } from 'next/font/google';
import UserDropdown from './user-dropdown';
import './globals.css';
import { Toaster } from 'sonner';

const fraunces = Fraunces({
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-fraunces',
  subsets: ['latin'],
});

const gabriela = Gabriela({
  weight: ['400'],
  variable: '--font-gabriela',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${fraunces.variable} ${gabriela.variable} antialiased`}
        >
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href={'/'}
              className="font-bold text-2xl flex gap-1 items-center"
            >
              <ChartColumnBig className="text-lime-500" /> NextCash
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center">
                  <Button asChild variant="link" className="text-white">
                    <SignInButton />
                  </Button>
                  <Button asChild variant={'link'} className="text-white">
                    <SignUpButton />
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <UserDropdown />
              </SignedIn>
            </div>
          </nav>
          {children}
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
